### ISSUE TITLE
File to File mounting fails

### ISSUE THREAD

**Issue by adshrc** [mobtitude/docker-vpn-pptp#10]
This mount solution, which actually mounts a file to a file, doesn't work on every filesystem.

Error:
mounting "localpath" to rootfs "dockerpath" caused "not a directory".

**Comment by pszalko** [comment]
Hi @unrl,

According to Docker's documentation, it is correct to mount file as a volume:
https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume

Have you checked on other images if mounting file as a volume works for you?

**Comment by adshrc** [comment]
Hi,

I don't know why, but it works now. Btw I'm using a compose.yml. Thanks for your support!

vpn:
  image: mobtitude/vpn-pptp
  container_name: vpn
  ports:
    - "1723:1723"
  privileged: true
  volumes:
    - /mnt/docker/vpn/chap-secrets:/etc/ppp/chap-secrets
