### ISSUE TITLE
can't run docker command from ubuntu 16.04

### ISSUE THREAD

**Issue by coney** [mobtitude/docker-vpn-pptp#11]
my os version : Ubuntu 16.04.1 LTS (Xenial Xerus)
docker version: Docker version 1.11.2, build b9f10c9

```
docker run -d --privileged -p 1723:1723 -v {local_path_to_chap_secrets}:/etc/ppp/chap-secrets mobtitude/vpn-pptp
docker: Error response from daemon: create {local_path_to_chap_secrets}: "{local_path_to_chap_secrets}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.
```

any ideas?

**Comment by nikotung** [comment]
@coney I think _{local_path_to_chap_secrets}_ just the placeholder ,it mean it should be changed to the real path of the chap-secrets of your host so that it can be mounted to the container.

**Comment by pszalko** [comment]
@coney I'm closing this issue as @NikoTung gave the correct answer to your question.
