### ISSUE TITLE
my config cannot init.

### ISSUE THREAD

**Issue by codingwesley** [mobtitude/docker-vpn-pptp#13]
# Secrets for authentication using PAP
# client    server      secret      acceptable local IP addresses
chenhuan    pptpd       chenhuan402    *
amy         pptpd       amy402         *
huanhuan    pptpd       huanhuan402    *

image is my config file

and command is `docker run -it --privileged -p 1723:1723 -v /root/chap-secrets:/etc/ppp/chap-secrets mobtitude/vpn-pptp`
cannot connect server.
can you help me?

**Comment by pszalko** [comment]
Please try following chap-secrets:

```
# Secrets for authentication using PAP
# client	server	secret		acceptable local IP addresses
chenhuan	*	chenhuan402	*
amy		*	amy402		*
huanhuan	*	huanhuan402	*
```
