### ISSUE TITLE
iptables issue

### ISSUE THREAD

**Issue by davidbullado** [mobtitude/docker-vpn-pptp#16]
Hi, I had to add theses rules, otherwise it doesn't works: 
iptables -A INPUT   -i ppp0 -j ACCEPT
iptables -A OUTPUT  -o ppp0 -j ACCEPT
iptables -A FORWARD -i ppp0 -j ACCEPT
iptables -A FORWARD -o ppp0 -j ACCEPT

**Comment by iKuiki** [comment]
I have the same problem

**Comment by pszalko** [comment]
Thank you guys for reporting this issue. 
@yinhui87 could you create pull request from your commit so I can merge it and release new version?

**Comment by ubaops** [comment]
how can I use more account? add iptables ppp1 ppp2 ?

**Comment by deba12** [comment]
Just use ppp+
