### ISSUE TITLE
Connects but No Internet

### ISSUE THREAD

**Issue by parsalotfy** [mobtitude/docker-vpn-pptp#23]
Hi,
I have done the instruction, the VPN connects successfully but there is no internet.
What should I do ?

**Comment by mrdaghestani** [comment]
Hi,
Same for me.
It connects but no internet...!

**Comment by parsalotfy** [comment]
> Hi,
> Same for me.
> It connects but no internet...!

What is the data center of your VPS ? Hetzner ?

**Comment by mrdaghestani** [comment]
It's BitCommand

**Comment by fozbek** [comment]
Hi, same for me. Hetzner and Scaleway.

Update
I recreated the 'chap-secrets' file and problem was fixed. It works on Hetzner.

**Comment by parsalotfy** [comment]
> Hi, same for me. Hetzner and Scaleway.
> 
> Update
> I recreated the 'chap-secrets' file and problem was fixed. It works on Hetzner.

Thank you for sharing , you just remove the file and create it again ?
no stopping the process or something else ???

**Comment by fozbek** [comment]
> > Hi, same for me. Hetzner and Scaleway.
> > Update
> > I recreated the 'chap-secrets' file and problem was fixed. It works on Hetzner.
> 
> Thank you for sharing , you just remove the file and create it again ?
> no stopping the process or something else ???

I stopped the container, actually i might have deleted it. And then deleted the file and created it again. Copied the content from readme and replaced *username* and *password*. I didn't touch to spaces. 
Make sure to the container can access to internet.
