### ISSUE TITLE
I get a problem when running it

### ISSUE THREAD

**Issue by ruandao** [mobtitude/docker-vpn-pptp#3]
this was the log:

ljy@ruandao:~/docker-vpn-pptp$ docker build -t ruandao/vpn .
Sending build context to Docker daemon 88.58 kB
Step 0 : FROM ubuntu:latest
 ---> 91e54dfb1179
Step 1 : MAINTAINER Przemek Szalko przemek@mobtitude.com
 ---> Running in 0e3501e28867
 ---> 9518a89488f7
Removing intermediate container 0e3501e28867
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 0dc86aac5c4e
 ---> 4075d35009e8
Removing intermediate container 0dc86aac5c4e
Step 3 : RUN apt-get update && apt-get install -y pptpd iptables
 ---> Running in bc65922086fc
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:1 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Get:2 http://archive.ubuntu.com trusty-security Release.gpg [933 B]
Hit http://archive.ubuntu.com trusty Release
Get:3 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
Get:4 http://archive.ubuntu.com trusty-security Release [63.5 kB]
Get:5 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:6 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:7 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:8 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:9 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:10 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:11 http://archive.ubuntu.com trusty-updates/main Sources [291 kB]
Get:12 http://archive.ubuntu.com trusty-updates/restricted Sources [4521 B]
Get:13 http://archive.ubuntu.com trusty-updates/universe Sources [169 kB]
Get:14 http://archive.ubuntu.com trusty-updates/main amd64 Packages [772 kB]
Get:15 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:16 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [404 kB]
Get:17 http://archive.ubuntu.com trusty-security/main Sources [118 kB]
Get:18 http://archive.ubuntu.com trusty-security/restricted Sources [1874 B]
Get:19 http://archive.ubuntu.com trusty-security/universe Sources [34.8 kB]
Get:20 http://archive.ubuntu.com trusty-security/main amd64 Packages [428 kB]
Get:21 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.8 kB]
Get:22 http://archive.ubuntu.com trusty-security/universe amd64 Packages [149 kB]
Fetched 21.2 MB in 13s (1594 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  bcrelay libnfnetlink0 libpcap0.8 libwrap0 libxtables10 ppp tcpd
The following NEW packages will be installed:
  bcrelay iptables libnfnetlink0 libpcap0.8 libwrap0 libxtables10 ppp pptpd
  tcpd
0 upgraded, 9 newly installed, 0 to remove and 1 not upgraded.
Need to get 897 kB of archives.
After this operation, 3655 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libnfnetlink0 amd64 1.0.1-2 [15.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libpcap0.8 amd64 1.5.3-2 [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libwrap0 amd64 7.6.q-25 [46.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libxtables10 amd64 1.4.21-1ubuntu1 [25.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main iptables amd64 1.4.21-1ubuntu1 [261 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main ppp amd64 2.4.5-5.1ubuntu2.2 [311 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main bcrelay amd64 1.3.4+27+gddb30f8-1ubuntu1 [13.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main pptpd amd64 1.3.4+27+gddb30f8-1ubuntu1 [91.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main tcpd amd64 7.6.q-25 [23.0 kB]
Fetched 897 kB in 6s (143 kB/s)
Selecting previously unselected package libnfnetlink0:amd64.
(Reading database ... 11541 files and directories currently installed.)
Preparing to unpack .../libnfnetlink0_1.0.1-2_amd64.deb ...
Unpacking libnfnetlink0:amd64 (1.0.1-2) ...
Selecting previously unselected package libpcap0.8:amd64.
Preparing to unpack .../libpcap0.8_1.5.3-2_amd64.deb ...
Unpacking libpcap0.8:amd64 (1.5.3-2) ...
Selecting previously unselected package libwrap0:amd64.
Preparing to unpack .../libwrap0_7.6.q-25_amd64.deb ...
Unpacking libwrap0:amd64 (7.6.q-25) ...
Selecting previously unselected package libxtables10.
Preparing to unpack .../libxtables10_1.4.21-1ubuntu1_amd64.deb ...
Unpacking libxtables10 (1.4.21-1ubuntu1) ...
Selecting previously unselected package iptables.
Preparing to unpack .../iptables_1.4.21-1ubuntu1_amd64.deb ...
Unpacking iptables (1.4.21-1ubuntu1) ...
Selecting previously unselected package ppp.
Preparing to unpack .../ppp_2.4.5-5.1ubuntu2.2_amd64.deb ...
 Removing any system startup links for /etc/init.d/ppp ...
Unpacking ppp (2.4.5-5.1ubuntu2.2) ...
Selecting previously unselected package bcrelay.
Preparing to unpack .../bcrelay_1.3.4+27+gddb30f8-1ubuntu1_amd64.deb ...
Unpacking bcrelay (1.3.4+27+gddb30f8-1ubuntu1) ...
Selecting previously unselected package pptpd.
Preparing to unpack .../pptpd_1.3.4+27+gddb30f8-1ubuntu1_amd64.deb ...
Unpacking pptpd (1.3.4+27+gddb30f8-1ubuntu1) ...
Selecting previously unselected package tcpd.
Preparing to unpack .../tcpd_7.6.q-25_amd64.deb ...
Unpacking tcpd (7.6.q-25) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libnfnetlink0:amd64 (1.0.1-2) ...
Setting up libpcap0.8:amd64 (1.5.3-2) ...
Setting up libwrap0:amd64 (7.6.q-25) ...
Setting up libxtables10 (1.4.21-1ubuntu1) ...
Setting up iptables (1.4.21-1ubuntu1) ...
Setting up ppp (2.4.5-5.1ubuntu2.2) ...
Setting up bcrelay (1.3.4+27+gddb30f8-1ubuntu1) ...
Setting up tcpd (7.6.q-25) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up pptpd (1.3.4+27+gddb30f8-1ubuntu1) ...

```
invoke-rc.d: policy-rc.d denied execution of start.    
```

Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Processing triggers for ureadahead (0.100.0-16) ...
 ---> 3299c03fcd1f
Removing intermediate container bc65922086fc
Step 4 : COPY ./etc/pptpd.conf /etc/pptpd.conf
 ---> f26941ceaad2
Removing intermediate container c792fe75d26c
Step 5 : COPY ./etc/ppp/pptpd-options /etc/ppp/pptpd-options
 ---> e4ab50a48c0b
Removing intermediate container 154301e7a9b6
Step 6 : COPY entrypoint.sh /entrypoint.sh
 ---> b39b664b48f0
Removing intermediate container 9ce2115d709f
Step 7 : RUN chmod 0700 /entrypoint.sh
 ---> Running in 7423f7c2d995
 ---> bc86c74d7934
Removing intermediate container 7423f7c2d995
Step 8 : ENTRYPOINT /entrypoint.sh
 ---> Running in 9620d5f9705e
 ---> 9ed928431e7f
Removing intermediate container 9620d5f9705e
Step 9 : CMD pptpd --fg
 ---> Running in 423a2c9be76c
 ---> d22d4ea278d3
Removing intermediate container 423a2c9be76c
Successfully built d22d4ea278d3

```
but when i run it, the system output this error:
```

ljy@ruandao:~/docker-vpn-pptp$ docker run -d --privileged -p 1723:1723 -v $(pwd)/vpnConf:/etc/ppp/chap-secrets  ruandao/vpn
31f93dae5d5edc84389678d720399d4522d9cc19536e845e403c922c29cbbc5b
Error response from daemon: Cannot start container 31f93dae5d5edc84389678d720399d4522d9cc19536e845e403c922c29cbbc5b: [8] System error: not a directory

```
the docker version:
```

ljy@ruandao:~/docker-vpn-pptp$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

```
thank you!
```

**Comment by dreamer2012** [comment]
I have got the same problem and don't know how to solve it.
My docker version is 1.9.1 and the host OS is Centos 7.
I am wondering if any problem with the kernel since the image is from ubuntu.
Desperate need for any help

**Comment by jgimenez** [comment]
You need to specify the full path to the chap-secrets file in your host machine.

**Comment by ruandao** [comment]
thank you!
