### ISSUE TITLE
docker image not have rsyslog

### ISSUE THREAD

**Issue by xiaoyawl** [mobtitude/docker-vpn-pptp#8]
Dockerfile Need add
apt-get install -y rsyslog

**Comment by pszalko** [comment]
Thank you for opening issue.
I suppose it was fixed in #7. Please let me know if this solution works for you.

**Comment by xiaoyawl** [comment]
@pszalko thx, yes need add rsyslog,just only this.

**Comment by pszalko** [comment]
I've released new bugfixing version 1.0.2. It will be available in Docker Hub in few minutes.
